package org.task_manager.backend.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.task_manager.backend.model.Report;
import org.task_manager.backend.model.User;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

public interface ReportRepository extends JpaRepository<Report, Long> {
    
    /**
     * Find reports generated by a specific user
     */
    List<Report> findByGeneratedBy(User user);
    
    /**
     * Find reports by type
     */
    List<Report> findByReportType(String reportType);
    
    /**
     * Find reports by status
     */
    List<Report> findByStatus(String status);
    
    /**
     * Find reports by format (CSV, PDF, EXCEL)
     */
    List<Report> findByFormat(String format);
    
    /**
     * Find reports generated by a user and of a specific type
     */
    List<Report> findByGeneratedByAndReportType(User user, String reportType);
    
    /**
     * Find reports generated between two dates
     */
    List<Report> findByGeneratedAtBetween(LocalDateTime startDate, LocalDateTime endDate);
    
    /**
     * Find reports generated by a user between two dates
     */
    List<Report> findByGeneratedByAndGeneratedAtBetween(User user, LocalDateTime startDate, LocalDateTime endDate);
    
    /**
     * Find completed reports ordered by generation date (newest first)
     */
    @Query("SELECT r FROM Report r WHERE r.status = 'COMPLETED' ORDER BY r.generatedAt DESC")
    List<Report> findCompletedReportsOrderByGeneratedAtDesc();
    
    /**
     * Find pending reports (not yet generated)
     */
    @Query("SELECT r FROM Report r WHERE r.status = 'PENDING' ORDER BY r.generatedAt ASC")
    List<Report> findPendingReports();
    
    /**
     * Find failed reports
     */
    @Query("SELECT r FROM Report r WHERE r.status = 'FAILED'")
    List<Report> findFailedReports();
    
    /**
     * Find reports by name (case-insensitive)
     */
    List<Report> findByReportNameContainingIgnoreCase(String reportName);
    
    /**
     * Find all reports ordered by generation date
     */
    @Query("SELECT r FROM Report r ORDER BY r.generatedAt DESC")
    List<Report> findAllOrderByGeneratedAtDesc();
    
    /**
     * Find reports expiring soon
     */
    @Query("SELECT r FROM Report r WHERE r.expiresAt IS NOT NULL AND r.expiresAt < :futureDate AND r.expiresAt > :currentDate")
    List<Report> findReportsExpiringBefore(@Param("currentDate") LocalDateTime currentDate, @Param("futureDate") LocalDateTime futureDate);
    
    /**
     * Count reports by type
     */
    long countByReportType(String reportType);
    
    /**
     * Count reports by status
     */
    long countByStatus(String status);
    
    /**
     * Count reports generated by user
     */
    long countByGeneratedBy(User user);
    
    /**
     * Find most recent report of a specific type
     */
    @Query("SELECT r FROM Report r WHERE r.reportType = :reportType ORDER BY r.generatedAt DESC LIMIT 1")
    Optional<Report> findMostRecentReportByType(@Param("reportType") String reportType);
    
    /**
     * Find total size of all reports (for storage monitoring)
     */
    @Query("SELECT COALESCE(SUM(r.fileSize), 0) FROM Report r")
    long getTotalReportSize();
    
    /**
     * Find reports generated by a user and not expired
     */
    @Query("SELECT r FROM Report r WHERE r.generatedBy.id = :userId AND (r.expiresAt IS NULL OR r.expiresAt > CURRENT_TIMESTAMP) ORDER BY r.generatedAt DESC")
    List<Report> findActiveReportsByUserId(@Param("userId") Long userId);
    
    /**
     * Delete expired reports (for cleanup)
     */
    long deleteByExpiresAtBefore(LocalDateTime date);
    
    /**
     * Find reports created in last N days
     */
    @Query("SELECT r FROM Report r WHERE r.generatedAt >= :dateThreshold ORDER BY r.generatedAt DESC")
    List<Report> findRecentReports(@Param("dateThreshold") LocalDateTime dateThreshold);
}
